from fastapi import FastAPI
from pydantic import BaseModel
import requests
import os

HF_API_URL = "https://api-inference.huggingface.co/models/google/flan-t5-large"
HF_TOKEN = os.getenv("HF_TOKEN")

app = FastAPI(title="Stitch QA Log Agent")


class LogAnalysisRequest(BaseModel):
    project_type: str
    command: str
    success: bool
    exit_code: int | None
    stdout: str
    stderr: str


@app.get("/")
def health_check():
    return {
        "service": "stitch-qa-log-agent",
        "status": "running",
        "llm_enabled": bool(HF_TOKEN)
    }


def rule_based_analysis(request: LogAnalysisRequest):
    issues = []
    warnings = []
    final_status = "PASS" if request.success else "FAIL"

    combined_logs = f"{request.stdout}\n{request.stderr}".lower()

    if "build success" in combined_logs:
        issues.append("Build completed successfully.")

    if "build failure" in combined_logs or "compilation failure" in combined_logs:
        issues.append("Build or compilation failure detected.")

    if "failures: 0" in combined_logs and "errors: 0" in combined_logs:
        issues.append("Tests completed without failures.")

    if "warning" in combined_logs:
        warnings.append("Warnings detected in execution logs.")

    if "mockito" in combined_logs and "dynamic loading of agents" in combined_logs:
        warnings.append(
            "Mockito dynamic agent warning detected. This is not a test failure, but it may require configuration updates for future JDK versions."
        )

    if request.exit_code not in (0, None):
        issues.append(f"Process exited with non-zero exit code: {request.exit_code}")

    return {
        "agent": "log-agent",
        "mode": "rule-based",
        "final_status": final_status,
        "summary": "Execution logs analyzed successfully.",
        "issues": issues,
        "warnings": warnings,
        "root_cause": "No blocking runtime error detected." if request.success else "Execution failed. Review errors and stack traces.",
        "recommendation": "Project passed current test execution." if request.success else "Fix the detected error and rerun Stitch QA."
    }


def build_prompt(request: LogAnalysisRequest):
    stdout_tail = request.stdout[-4000:] if request.stdout else "No stdout output."
    stderr_tail = request.stderr[-4000:] if request.stderr else "No stderr output."

    return f"""
You are an expert software QA engineer.

Analyze this software build/test execution result.

Project Type:
{request.project_type}

Command:
{request.command}

Exit Code:
{request.exit_code}

Execution Success:
{request.success}

STDOUT:
{stdout_tail}

STDERR:
{stderr_tail}

Return a concise QA analysis with:
1. Summary
2. Root Cause
3. Issues
4. Warnings
5. Recommendation
6. Final Status as PASS or FAIL
"""


def call_llm(prompt: str):
    if not HF_TOKEN:
        raise RuntimeError("HF_TOKEN is not configured.")

    headers = {
        "Authorization": f"Bearer {HF_TOKEN}",
        "Content-Type": "application/json"
    }

    payload = {
        "inputs": prompt,
        "parameters": {
            "max_new_tokens": 300,
            "return_full_text": False
        }
    }

    response = requests.post(
        HF_API_URL,
        headers=headers,
        json=payload,
        timeout=60
    )

    response.raise_for_status()
    return response.json()


def extract_llm_text(result):
    if isinstance(result, list) and result:
        first_item = result[0]

        if isinstance(first_item, dict):
            return first_item.get("generated_text", str(first_item))

    if isinstance(result, dict):
        return result.get("generated_text", str(result))

    return str(result)


@app.post("/analyze")
def analyze_logs(request: LogAnalysisRequest):
    fallback_result = rule_based_analysis(request)

    try:
        prompt = build_prompt(request)
        llm_result = call_llm(prompt)
        llm_text = extract_llm_text(llm_result)

        return {
            "agent": "log-agent",
            "mode": "llm",
            "final_status": "PASS" if request.success else "FAIL",
            "summary": llm_text,
            "issues": fallback_result["issues"],
            "warnings": fallback_result["warnings"],
            "root_cause": "Generated by LLM. See summary for detailed reasoning.",
            "recommendation": "Review the LLM summary and fallback issue list before taking action."
        }

    except Exception as error:
        fallback_result["llm_error"] = str(error)
        return fallback_result