from fastapi import FastAPI
from pydantic import BaseModel
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import os

HF_MODEL = os.getenv("HF_MODEL", "google/flan-t5-small")

tokenizer = None
model = None

app = FastAPI(title="Stitch QA Log Agent")


class LogAnalysisRequest(BaseModel):
    project_type: str
    command: str
    success: bool
    exit_code: int | None
    stdout: str
    stderr: str


@app.get("/")
def health_check():
    return {
        "service": "stitch-qa-log-agent",
        "status": "running",
        "llm_enabled": True,
        "llm_mode": "local-transformers",
        "model": HF_MODEL
    }


def load_model():
    global tokenizer, model

    if tokenizer is None or model is None:
        tokenizer = AutoTokenizer.from_pretrained(HF_MODEL)
        model = AutoModelForSeq2SeqLM.from_pretrained(HF_MODEL)

    return tokenizer, model


def rule_based_analysis(request: LogAnalysisRequest):
    issues = []
    warnings = []
    final_status = "PASS" if request.success else "FAIL"

    combined_logs = f"{request.stdout}\n{request.stderr}".lower()

    if "build success" in combined_logs:
        issues.append("Build completed successfully.")

    if "build failure" in combined_logs or "compilation failure" in combined_logs:
        issues.append("Build or compilation failure detected.")

    if "failures: 0" in combined_logs and "errors: 0" in combined_logs:
        issues.append("Tests completed without failures.")

    if "warning" in combined_logs:
        warnings.append("Warnings detected in execution logs.")

    if "mockito" in combined_logs and "dynamic loading of agents" in combined_logs:
        warnings.append(
            "Mockito dynamic agent warning detected. This is not a test failure, but it may require configuration updates for future JDK versions."
        )

    if request.exit_code not in (0, None):
        issues.append(f"Process exited with non-zero exit code: {request.exit_code}")

    return {
        "agent": "log-agent",
        "mode": "rule-based",
        "final_status": final_status,
        "summary": "Execution logs analyzed successfully.",
        "issues": issues,
        "warnings": warnings,
        "root_cause": "No blocking runtime error detected." if request.success else "Execution failed. Review errors and stack traces.",
        "recommendation": "Project passed current test execution." if request.success else "Fix the detected error and rerun Stitch QA."
    }


def build_prompt(request: LogAnalysisRequest):
    stdout_tail = request.stdout[-1200:] if request.stdout else "No stdout output."
    stderr_tail = request.stderr[-1200:] if request.stderr else "No stderr output."

    return f"""
Analyze this software QA execution.

Project type: {request.project_type}
Command: {request.command}
Exit code: {request.exit_code}
Success: {request.success}

Build output:
{stdout_tail}

Warnings or errors:
{stderr_tail}

Write short QA result:
Summary:
Root cause:
Issues:
Warnings:
Recommendation:
Final status:
"""


def call_llm(prompt: str):
    active_tokenizer, active_model = load_model()

    inputs = active_tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )

    outputs = active_model.generate(
        **inputs,
        max_new_tokens=180,
        do_sample=False
    )

    return active_tokenizer.decode(outputs[0], skip_special_tokens=True)


@app.post("/analyze")
def analyze_logs(request: LogAnalysisRequest):
    fallback_result = rule_based_analysis(request)

    try:
        prompt = build_prompt(request)
        llm_text = call_llm(prompt)

        return {
            "agent": "log-agent",
            "mode": "llm",
            "final_status": "PASS" if request.success else "FAIL",
            "summary": llm_text,
            "issues": fallback_result["issues"],
            "warnings": fallback_result["warnings"],
            "root_cause": "Generated by local FLAN-T5 model. See summary for detailed reasoning.",
            "recommendation": "Review the LLM summary and fallback issue list before taking action."
        }

    except Exception as error:
        fallback_result["llm_error"] = repr(error)
        fallback_result["summary"] = f"LLM failed, fallback rule-based analysis used. Error: {repr(error)}"
        return fallback_result